export const SALESPEOPLE = [
    "Abebe Girma",
    "Mekdes Tadesse",
    "Yonas Hailu",
    "Selam Bekele",
    "Dawit Mengesha",
    "Tigist Alemu",
    "Bereket Wolde",
];

export const initialVisits = [
    {
        id: "v-001",
        timestamp: new Date("2026-07-06T08:15:00").toISOString(),
        salesperson: "Abebe Girma",
        address: "Bole Sub-City, Woreda 03, House No. 512, Addis Ababa",
        latitude: "9.0227",
        longitude: "38.7469",
        clientManager: "Ato Tesfaye Kebede",
        houseSize: 320,
    },
    {
        id: "v-002",
        timestamp: new Date("2026-07-06T09:30:00").toISOString(),
        salesperson: "Mekdes Tadesse",
        address: "Kirkos Sub-City, Woreda 07, Sar Bet, Addis Ababa",
        latitude: "9.0056",
        longitude: "38.7578",
        clientManager: "W/ro Almaz Haile",
        houseSize: 180,
    },
    {
        id: "v-003",
        timestamp: new Date("2026-07-05T14:00:00").toISOString(),
        salesperson: "Yonas Hailu",
        address: "Yeka Sub-City, Woreda 11, Gerji, Addis Ababa",
        latitude: "9.0341",
        longitude: "38.8012",
        clientManager: "Ato Mulugeta Seyoum",
        houseSize: 450,
    },
    {
        id: "v-004",
        timestamp: new Date("2026-07-05T10:45:00").toISOString(),
        salesperson: "Abebe Girma",
        address: "Nifas Silk-Lafto, Woreda 02, Mexico Area, Addis Ababa",
        latitude: "8.9806",
        longitude: "38.7392",
        clientManager: "W/ro Hiwot Tesfaye",
        houseSize: 260,
    },
    {
        id: "v-005",
        timestamp: new Date("2026-07-04T16:20:00").toISOString(),
        salesperson: "Selam Bekele",
        address: "Arada Sub-City, Woreda 09, Piassa, Addis Ababa",
        latitude: "9.0358",
        longitude: "38.7469",
        clientManager: "Ato Berhane Gebre",
        houseSize: 140,
    },
    {
        id: "v-006",
        timestamp: new Date("2026-07-04T11:00:00").toISOString(),
        salesperson: "Dawit Mengesha",
        address: "Lideta Sub-City, Woreda 05, 22-Mazoria, Addis Ababa",
        latitude: "9.0112",
        longitude: "38.7378",
        clientManager: "W/rt Selamawit Worku",
        houseSize: 390,
    },
    {
        id: "v-007",
        timestamp: new Date("2026-07-03T09:05:00").toISOString(),
        salesperson: "Tigist Alemu",
        address: "Kolfe Keraniyo, Woreda 14, Ayertena, Addis Ababa",
        latitude: "9.0437",
        longitude: "38.7155",
        clientManager: "Ato Kebede Desta",
        houseSize: 210,
    },
];
